services:
  main:
    image: ${IMAGE:-""}
    container_name: omgafoo_main
    environment:
      - APP_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: omga.foo
      caddy.reverse_proxy: "{{upstreams 80}}"